### ISSUE TITLE
Download pay apps 

### ISSUE THREAD

**Issue by HakimGhanem** [ClaudiuGeorgiu/PlaystoreDownloader#13]
I've downloaded an app on my phone and once I tried to download the package I get this error. How can we handle pay apps ? (I turned off the Less secure app access) 
```
python download.py "com.mlb.RBIBaseball"
26/02/2019 13:32:48> [ERROR][download()] Error for app "com.mlb.RBIBaseball": The Play Store application on your device is outdated and does not support this purchase.
here
Error when downloading "com.mlb.RBIBaseball".
```

**Comment by ClaudiuGeorgiu** [comment]
Hi, thanks for submitting the issue. I'm able to reproduce the error while trying to download a purchased app and I think I found a solution. I need to do some more tests, but I'll update the code as soon as I have everything working.

**Comment by ClaudiuGeorgiu** [comment]
I made a commit on the `develop` branch (8dffd421c656c882313ea905af3d98c36340be89) that should fix the issue (I tested it using 2 purchased apps I have on my account).

**Comment by HakimGhanem** [comment]
Hi, thanks for your answers and modifications, but I still have the same error and still can't download purchased apps.

**Comment by ClaudiuGeorgiu** [comment]
I'm sorry, but with the purchased apps I have on my account the download now works, so I cannot replicate the problem. I'll leave this issue open, thanks for reporting.

**Comment by ClaudiuGeorgiu** [comment]
Hi @HakimGhanem, I don't know if you are still using this project, but latest commit on `develop` branch 7be39bfe43a0571fc4308edef537bc1c071b20e5 could solve some issues with the purchased apps.

**Comment by HakimGhanem** [comment]
Hi Claudiu, I am not working with Google Playstore anymore but thank you
for letting me know :)

Hakim GHANEM
